const TIME_CHECK_PROXY = 60000 // 1minute
const TIME_UPLOAD_ACTIVITY = 300000
const TIME_GET_LOCAL_PROCESS_ACTIVITY = 60000
const TIME_UPDATE_RULE_WEB = 600000 // 10 minutes
const TIME_UPDATE_RESTRICT_TIME = 300000 // 5 minute
const TIME_UPDATE_ZVELO_KEY = 7200000 // 2 hours
const TIME_CHECK_LOCK_SCREEN = 30000 // 30s

export {
    TIME_CHECK_PROXY,
    TIME_UPLOAD_ACTIVITY,
    TIME_GET_LOCAL_PROCESS_ACTIVITY,
    TIME_UPDATE_RULE_WEB,
    TIME_UPDATE_RESTRICT_TIME,
    TIME_UPDATE_ZVELO_KEY,
    TIME_CHECK_LOCK_SCREEN
}